export const trendingMovies = [
    {
        id: 1,
        img: "https://picsum.photos/seed/morbius/400/600",
        heroImg: "https://picsum.photos/seed/morbius/1280/720",
        title: "Interstellar",
        duration: "2h 49min",
        views: "12K",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        year: 2014,
        languages: ["English", "Russian"],
        imdbRating: 4.8,
        streamvibeRating: 5,
        genres: ["Sci-Fi", "Drama"],
        director: { name: "Christopher Nolan", from: "UK", img: "https://picsum.photos/seed/dir1/50/50" },
        music: { name: "Hans Zimmer", from: "Germany", img: "https://picsum.photos/seed/mus1/50/50" },
        cast: [
            { name: "Matthew McConaughey", img: "https://picsum.photos/seed/cast1a/80/80" },
            { name: "Anne Hathaway", img: "https://picsum.photos/seed/cast1b/80/80" },
            { name: "Jessica Chastain", img: "https://picsum.photos/seed/cast1c/80/80" },
            { name: "Michael Caine", img: "https://picsum.photos/seed/cast1d/80/80" },
        ],
        reviews: [
            { name: "Alex Johnson", from: "USA", rating: 5, text: "One of the greatest sci-fi films ever made. Nolan outdid himself with this masterpiece." },
            { name: "Maria Garcia", from: "Spain", rating: 4.5, text: "Visually stunning and emotionally gripping. Hans Zimmer's score is unforgettable." },
        ],
    },
    {
        id: 2,
        img: "https://picsum.photos/seed/jaan/400/600",
        heroImg: "https://picsum.photos/seed/jaan/1280/720",
        title: "The Dark Knight",
        duration: "2h 32min",
        views: "20K",
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        year: 2008,
        languages: ["English", "Spanish", "French"],
        imdbRating: 4.9,
        streamvibeRating: 5,
        genres: ["Action", "Crime", "Drama"],
        director: { name: "Christopher Nolan", from: "UK", img: "https://picsum.photos/seed/dir2/50/50" },
        music: { name: "Hans Zimmer", from: "Germany", img: "https://picsum.photos/seed/mus2/50/50" },
        cast: [
            { name: "Christian Bale", img: "https://picsum.photos/seed/cast2a/80/80" },
            { name: "Heath Ledger", img: "https://picsum.photos/seed/cast2b/80/80" },
            { name: "Aaron Eckhart", img: "https://picsum.photos/seed/cast2c/80/80" },
            { name: "Maggie Gyllenhaal", img: "https://picsum.photos/seed/cast2d/80/80" },
        ],
        reviews: [
            { name: "James Wilson", from: "UK", rating: 5, text: "Heath Ledger's Joker is the most iconic villain in cinema history. A perfect film." },
            { name: "Sophie Martin", from: "France", rating: 5, text: "Redefines what a superhero movie can be. Dark, complex and thrilling." },
        ],
    },
    {
        id: 3,
        img: "https://picsum.photos/seed/suraj/400/600",
        heroImg: "https://picsum.photos/seed/suraj/1280/720",
        title: "Inception",
        duration: "2h 28min",
        views: "15K",
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        year: 2010,
        languages: ["English", "Japanese", "French"],
        imdbRating: 4.7,
        streamvibeRating: 4.5,
        genres: ["Action", "Sci-Fi", "Thriller"],
        director: { name: "Christopher Nolan", from: "UK", img: "https://picsum.photos/seed/dir3/50/50" },
        music: { name: "Hans Zimmer", from: "Germany", img: "https://picsum.photos/seed/mus3/50/50" },
        cast: [
            { name: "Leonardo DiCaprio", img: "https://picsum.photos/seed/cast3a/80/80" },
            { name: "Joseph Gordon-Levitt", img: "https://picsum.photos/seed/cast3b/80/80" },
            { name: "Elliot Page", img: "https://picsum.photos/seed/cast3c/80/80" },
            { name: "Tom Hardy", img: "https://picsum.photos/seed/cast3d/80/80" },
        ],
        reviews: [
            { name: "David Kim", from: "South Korea", rating: 5, text: "Mind-bending storytelling at its finest. Every rewatch reveals something new." },
            { name: "Emma Brown", from: "Australia", rating: 4.5, text: "Brilliantly crafted. The rotating hallway scene alone is worth the watch." },
        ],
    },
    {
        id: 4,
        img: "https://picsum.photos/seed/pathan/400/600",
        heroImg: "https://picsum.photos/seed/pathan/1280/720",
        title: "The Godfather",
        duration: "2h 55min",
        views: "18K",
        description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        year: 1972,
        languages: ["English", "Italian", "Sicilian"],
        imdbRating: 5,
        streamvibeRating: 5,
        genres: ["Crime", "Drama"],
        director: { name: "Francis Ford Coppola", from: "USA", img: "https://picsum.photos/seed/dir4/50/50" },
        music: { name: "Nino Rota", from: "Italy", img: "https://picsum.photos/seed/mus4/50/50" },
        cast: [
            { name: "Marlon Brando", img: "https://picsum.photos/seed/cast4a/80/80" },
            { name: "Al Pacino", img: "https://picsum.photos/seed/cast4b/80/80" },
            { name: "James Caan", img: "https://picsum.photos/seed/cast4c/80/80" },
            { name: "Diane Keaton", img: "https://picsum.photos/seed/cast4d/80/80" },
        ],
        reviews: [
            { name: "Roberto Ferrari", from: "Italy", rating: 5, text: "The greatest film ever made. A timeless masterpiece of storytelling and performance." },
            { name: "Linda Chen", from: "USA", rating: 5, text: "Marlon Brando is extraordinary. Every scene is perfect." },
        ],
    },
    {
        id: 5,
        img: "https://picsum.photos/seed/antman/400/600",
        heroImg: "https://picsum.photos/seed/antman/1280/720",
        title: "Pulp Fiction",
        duration: "2h 34min",
        views: "14K",
        description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        year: 1994,
        languages: ["English", "Spanish", "French"],
        imdbRating: 4.8,
        streamvibeRating: 4.5,
        genres: ["Crime", "Drama", "Thriller"],
        director: { name: "Quentin Tarantino", from: "USA", img: "https://picsum.photos/seed/dir5/50/50" },
        music: { name: "Various Artists", from: "USA", img: "https://picsum.photos/seed/mus5/50/50" },
        cast: [
            { name: "John Travolta", img: "https://picsum.photos/seed/cast5a/80/80" },
            { name: "Uma Thurman", img: "https://picsum.photos/seed/cast5b/80/80" },
            { name: "Samuel L. Jackson", img: "https://picsum.photos/seed/cast5c/80/80" },
            { name: "Bruce Willis", img: "https://picsum.photos/seed/cast5d/80/80" },
        ],
        reviews: [
            { name: "Tom Anderson", from: "USA", rating: 5, text: "Tarantino at his absolute best. Unforgettable dialogue and non-linear storytelling." },
            { name: "Yuki Tanaka", from: "Japan", rating: 4.5, text: "Revolutionary filmmaking. Changed cinema forever." },
        ],
    },
];

export const mustWatchMovies = [
    {
        id: 6,
        img: "https://picsum.photos/seed/kantara/400/600",
        heroImg: "https://picsum.photos/seed/kantara/1280/720",
        title: "Schindler's List",
        duration: "3h 15min",
        rating: 5,
        views: "22K",
        description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        year: 1993,
        languages: ["English", "Hebrew", "German", "Polish"],
        imdbRating: 4.9,
        streamvibeRating: 5,
        genres: ["Biography", "Drama", "History"],
        director: { name: "Steven Spielberg", from: "USA", img: "https://picsum.photos/seed/dir6/50/50" },
        music: { name: "John Williams", from: "USA", img: "https://picsum.photos/seed/mus6/50/50" },
        cast: [
            { name: "Liam Neeson", img: "https://picsum.photos/seed/cast6a/80/80" },
            { name: "Ben Kingsley", img: "https://picsum.photos/seed/cast6b/80/80" },
            { name: "Ralph Fiennes", img: "https://picsum.photos/seed/cast6c/80/80" },
            { name: "Caroline Goodall", img: "https://picsum.photos/seed/cast6d/80/80" },
        ],
        reviews: [
            { name: "Anna Kowalski", from: "Poland", rating: 5, text: "A devastating and important film. Spielberg created something truly unforgettable." },
            { name: "Michael Cohen", from: "Israel", rating: 5, text: "Essential viewing for every human being. Powerful beyond words." },
        ],
    },
    {
        id: 7,
        img: "https://picsum.photos/seed/pushpa/400/600",
        heroImg: "https://picsum.photos/seed/pushpa/1280/720",
        title: "The Shawshank Redemption",
        duration: "2h 22min",
        rating: 5,
        views: "25K",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        year: 1994,
        languages: ["English"],
        imdbRating: 5,
        streamvibeRating: 5,
        genres: ["Drama"],
        director: { name: "Frank Darabont", from: "USA", img: "https://picsum.photos/seed/dir7/50/50" },
        music: { name: "Thomas Newman", from: "USA", img: "https://picsum.photos/seed/mus7/50/50" },
        cast: [
            { name: "Tim Robbins", img: "https://picsum.photos/seed/cast7a/80/80" },
            { name: "Morgan Freeman", img: "https://picsum.photos/seed/cast7b/80/80" },
            { name: "Bob Gunton", img: "https://picsum.photos/seed/cast7c/80/80" },
            { name: "William Sadler", img: "https://picsum.photos/seed/cast7d/80/80" },
        ],
        reviews: [
            { name: "Chris Walker", from: "USA", rating: 5, text: "The greatest story of hope and friendship ever put to film. Morgan Freeman is incredible." },
            { name: "Laura Bianchi", from: "Italy", rating: 5, text: "I cry every single time. A timeless classic that restores your faith in humanity." },
        ],
    },
    {
        id: 8,
        img: "https://picsum.photos/seed/bladerunner/400/600",
        heroImg: "https://picsum.photos/seed/bladerunner/1280/720",
        title: "Forrest Gump",
        duration: "2h 22min",
        rating: 4,
        views: "19K",
        description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold through the perspective of an Alabama man with an extraordinary gift.",
        year: 1994,
        languages: ["English", "Vietnamese"],
        imdbRating: 4.7,
        streamvibeRating: 4.5,
        genres: ["Drama", "Romance"],
        director: { name: "Robert Zemeckis", from: "USA", img: "https://picsum.photos/seed/dir8/50/50" },
        music: { name: "Alan Silvestri", from: "USA", img: "https://picsum.photos/seed/mus8/50/50" },
        cast: [
            { name: "Tom Hanks", img: "https://picsum.photos/seed/cast8a/80/80" },
            { name: "Robin Wright", img: "https://picsum.photos/seed/cast8b/80/80" },
            { name: "Gary Sinise", img: "https://picsum.photos/seed/cast8c/80/80" },
            { name: "Sally Field", img: "https://picsum.photos/seed/cast8d/80/80" },
        ],
        reviews: [
            { name: "Sarah Thompson", from: "USA", rating: 5, text: "Life is like a box of chocolates. Tom Hanks delivers the performance of a lifetime." },
            { name: "Pierre Dubois", from: "France", rating: 4, text: "Heartwarming and deeply moving. A celebration of the American spirit." },
        ],
    },
    {
        id: 9,
        img: "https://picsum.photos/seed/adipurush/400/600",
        heroImg: "https://picsum.photos/seed/adipurush/1280/720",
        title: "The Matrix",
        duration: "2h 16min",
        rating: 4,
        views: "17K",
        description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        year: 1999,
        languages: ["English", "French", "Spanish"],
        imdbRating: 4.7,
        streamvibeRating: 4.5,
        genres: ["Action", "Sci-Fi"],
        director: { name: "The Wachowskis", from: "USA", img: "https://picsum.photos/seed/dir9/50/50" },
        music: { name: "Don Davis", from: "USA", img: "https://picsum.photos/seed/mus9/50/50" },
        cast: [
            { name: "Keanu Reeves", img: "https://picsum.photos/seed/cast9a/80/80" },
            { name: "Laurence Fishburne", img: "https://picsum.photos/seed/cast9b/80/80" },
            { name: "Carrie-Anne Moss", img: "https://picsum.photos/seed/cast9c/80/80" },
            { name: "Hugo Weaving", img: "https://picsum.photos/seed/cast9d/80/80" },
        ],
        reviews: [
            { name: "Kevin Park", from: "South Korea", rating: 5, text: "Revolutionary visual effects and a mind-blowing story. Changed action cinema forever." },
            { name: "Nina Volkov", from: "Russia", rating: 4.5, text: "What is real? This film makes you question everything. Keanu Reeves is iconic." },
        ],
    },
];